# Generated by Django 3.0.6 on 2020-05-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_sprint_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Descriptiopn'),
        ),
        migrations.AddField(
            model_name='team',
            name='website',
            field=models.CharField(blank=True, max_length=200, verbose_name='website'),
        ),
    ]
